# Generated by Django 5.1.1 on 2025-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=200),
            preserve_default=False,
        ),
    ]
